app = "el-nombre-de-tu-app"
primary_region = "mia" # Puedes cambiar la región (ej. mia = Miami)

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = "off" # Evita que tu servidor se apague si no hay nadie conectado
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443
